### ISSUE TITLE
WinFsp 1.6 won't install after uninstalling previous version and rebooting  first

### ISSUE THREAD

**Issue by bobbyjacob** [billziss-gh/winfsp#304]
## Bug Report

Uninstalled previous WinFsp (don't remember what version). Rebooted. Tried to install 1.6. It gives following error message: "The WinFsp service appears to be running. If you just uninstalled WinFsp please restart your computer. If you are running a development version of WinFsp please remove it before proceeding."

Rebooting several times gives same error.

### How to Reproduce

Uninstall WinFsp. Reboot. Install WinFsp (winfsp-1.6.20027.msi).

### Behaviors

Installs.

### Environment

OS Version:                10.0.18362 N/A Build 18362
WinFsp version and build: winfsp-1.6.20027.msi
see attached diag.bat output
[diag.bat.txt](https://github.com/billziss-gh/winfsp/files/4606771/diag.bat.txt)

**Comment by billziss-gh** [comment]
This is expected behavior if you do not reboot. Are you saying that the problem persists even after you reboot?

**Comment by bobbyjacob** [comment]
Yes, I rebooted several times. Here's the error I think I made:

1. I uninstalled WinFsp (previous version). I was then prompted to reboot my computer.
2. I rebooted my computer.
3. I tried to install WinFsp 1.6 but could not.
4. Rebooted muliple times; didn't help.

What I should have done:
Ran the installer for 1.6 without uninstalling previous version first.

Let me know if that helps.

**Comment by billziss-gh** [comment]
I do not believe you have made any mistake. The correct procedure is to uninstall the previous version, reboot if requested and the install the latest version.

For some reason the driver gets reloaded after every reboot. Perhaps the driver registration was changed somehow to start the driver during system startup, or perhaps a file system that runs early during system startup is using it. This is certainly not something that WinFsp does on its own.

Is it possible to start an Administrator command prompt and run `sc delete WinFsp`? This should make sure to mark the driver for deletion. Then a reboot should make sure that it does not run any more.

**Comment by bobbyjacob** [comment]
Ran `sc delete WinFsp` in Administrator command prompt. Got error: `[SC] DeleteService FAILED 1072:`
I looked up that error and found this link on stack overflow: [(SC) DeleteService FAILED 1072](https://stackoverflow.com/questions/305037/sc-deleteservice-failed-1072)

I tried the method to remove WinFsp from the registry. There was an entry for it at `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Service`.

Rebooted my computer. Same problem. Got busy with work. I must have rebooted my computer several times since then. I went back to this today and tried the `sc delete WinFsp` command again and got a different code: 1060. I tried to install WinFsp this time and it worked. So I'm not sure if its the reboots or the removal of the line from the registry that made this work. 

Thanks for your help!

**Comment by billziss-gh** [comment]
The error code 1072 means that the service is marked for deletion. This happens when a service or driver is deleted but cannot be unloaded for some reason. However a reboot should always fix this and I have never seen this status persist after a reboot.

The error code 1060 means that the service (or driver) does not exist, which is what we wanted to do! It is likely that this happened because you removed the registry entry for the driver.

Both error codes can be found here:

[System Error Codes (1000-1299)](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1000-1299-)

A simple reboot should have been sufficient to fully uninstall WinFsp. I cannot think or guess of why this would not happen in your case. It does point to some potential system corruption or other system problem.

In any case I am closing this but please reopen if the problem persists.

**Comment by StefansArya** [comment]
I also have a problem on my first install.
It says older version was installed, but I never installed in the past and just found this project today.

![y8SEsts8E9](https://user-images.githubusercontent.com/11073373/87865076-b65e4780-c99a-11ea-8f5d-367f5b8907ff.gif)
Win 10 Build 18362

I'm not sure if the installer trying to figure if it was installed by checking some used port or used drive label 😅

**Comment by DartPower** [comment]
Also have this problem...

**Comment by DartPower** [comment]
Resolved problem in my situation, fully removed "Disk O" by MailRu Group (+removed driver/service)
And re-installed. All ok

**Comment by billziss-gh** [comment]
@DartPower thanks for the hint. It might be that someone is using a modified version of WinFsp which unfortunately interferes with the releases available via this project.

**Comment by divo1** [comment]
I also have this problem. I had some old version. I uninstalled it today and reboot computer. After this I tried install new version: 1.8. I had the same error message as author "The WinFsp service appears to be running". When I tried: `sc delete WinFsp` I get 1072 error.

**Comment by inspaer90** [comment]
I am also solved this problem by removing Disk O program. It is another soft for mounting cloud drives.

**Comment by anthonyfee** [comment]
I was battling with this same issue today. Just in case it helps anyone!

I shutdown the system many times but was still seeing the error. In the end I said I would try a system reboot instead of shutdown to cover all my bases, and it worked. The system reboot is clearly taking different actions than a normal shutdown and boot sequence.

**Comment by brian6932** [comment]
Hey I noticed that fsptool has a driver load and unload feature in the code, however this argument was not in the current release bin I tested, is there a way to execute this? Do I need to build it myself?
https://github.com/winfsp/winfsp/blob/9747af22e85ffbcb0766276d6def691d4419fd2a/src/fsptool/fsptool.c#L68-L69

**Comment by billziss-gh** [comment]
@brian6932 this will only work in the upcoming 2.0 releases, which will have the ability to unload the driver. It will not work in any of the current releases.
